version: '3'

services:
  nodejsapp:
    build: .
    restart: always
    ports:
      - ${SERVER_PORT}:3000
    env_file:
      - ./docker-compose.prod1.env
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_HOSTNAME=${MONGODB_HOSTNAME}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_PORT=${MONGODB_PORT}

      - BLOCKCYPHER_TOKEN=${BLOCKCYPHER_TOKEN}

      - WEBHOOK_ENDPOINT=${WEBHOOK_ENDPOINT}